---
- name: ensure screen package
  include_role:
    name: "damex.package"
  vars:
    package_packages:
      - name: "{{ screen_package_name }}"
        version: "{{ screen_package_version }}"
        state: "{{ screen_package_state }}"
