---
- name: ensure screen package is installed
  apt:
    pkg: "{{ item }}"
    install_recommends: false
    state: "present"
    update_cache: true
    cache_valid_time: 86400
  with_items:
    - screen
  become: true
  when: ansible_distribution == 'Debian'

- name: ensure screen package is installed
  yum:
    name: "{{ item }}"
    state: "present"
  with_items:
    - screen
  become: true
  when: ansible_distribution == 'CentOS'
